global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
